export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const PRODUCT_CREATE = 'PRODUCT_CREATE';
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';
export const PRODUCT_CREATE_CHANGE = 'PRODUCT_CREATE_CHANGE';


