export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const PRODUCT_CREATE = 'PRODUCT_CREATE';
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';
export const PRODUCT_CREATE_CHANGE = 'PRODUCT_CREATE_CHANGE';

export const DOCUMENT_LIST = 'DOCUMENT_LIST';
export const DOCUMENT_DETAILS = 'DOCUMENT_DETAILS';
export const DOCUMENT_DELETE = 'DOCUMENT_DELETE';
export const DOCUMENT_CREATE = 'DOCUMENT_CREATE';
export const DOCUMENT_UPDATE = 'DOCUMENT_UPDATE';
export const DOCUMENT_CREATE_CHANGE = 'DOCUMENT_CREATE_CHANGE';
